driver:
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.scheduler.global: 'true'
    io.rancher.container.agent.role: 'environment'
  privileged: true
  pid: host
  volumes:
    - /lib/modules:/lib/modules:ro
    - /proc:/host/proc
    - /var/run:/host/var/run
    - /dev:/host/dev
    - /etc/docker/plugins:/etc/docker/plugins
    - /var/lib/rancher/longhorn:/var/lib/rancher/longhorn
  image: yasker/longhorn:dd1fe7f
  command:
    - launch-driver
    - volumedriver
  environment:
    RANCHER_CLIENT_DEBUG: true

storagepool:
  labels:
    io.rancher.container.create_agent: 'true'
  image: yasker/longhorn:dd1fe7f
  command:
    - launch-driver
    - storagepool
